USE [master]
GO

/****** Object:  Database [Waffle]    Script Date: 01/18/2015 23:21:29 ******/
CREATE DATABASE [Waffle] ON  PRIMARY 
( NAME = N'Waffle', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\Waffle.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Waffle_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\Waffle_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Waffle] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Waffle].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Waffle] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Waffle] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Waffle] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Waffle] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Waffle] SET ARITHABORT OFF 
GO

ALTER DATABASE [Waffle] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Waffle] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Waffle] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Waffle] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Waffle] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Waffle] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Waffle] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Waffle] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Waffle] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Waffle] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Waffle] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Waffle] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Waffle] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Waffle] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Waffle] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Waffle] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Waffle] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Waffle] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Waffle] SET  READ_WRITE 
GO

ALTER DATABASE [Waffle] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Waffle] SET  MULTI_USER 
GO

ALTER DATABASE [Waffle] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Waffle] SET DB_CHAINING OFF 
GO


